// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlgj7wZFjZuTnYcrBHe3iludPguj04-vA',
    appId: '1:303920074408:android:a2cb04be14cc58479f3c9d',
    messagingSenderId: '303920074408',
    projectId: 'parkingapp-86b91',
    storageBucket: 'parkingapp-86b91.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwlQFQMZZ-rQgDNG9TtXQbd9zgv7223xc',
    appId: '1:303920074408:web:ff9cccc9375580679f3c9d',
    messagingSenderId: '303920074408',
    projectId: 'parkingapp-86b91',
    authDomain: 'parkingapp-86b91.firebaseapp.com',
    storageBucket: 'parkingapp-86b91.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwlQFQMZZ-rQgDNG9TtXQbd9zgv7223xc',
    appId: '1:303920074408:web:19a1bd54fb62d8c19f3c9d',
    messagingSenderId: '303920074408',
    projectId: 'parkingapp-86b91',
    authDomain: 'parkingapp-86b91.firebaseapp.com',
    storageBucket: 'parkingapp-86b91.firebasestorage.app',
  );

}